<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="10" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="MosaicSuite" duration-ms="22866" started-at="2018-05-25T13:03:53Z" finished-at="2018-05-25T13:04:16Z">
    <groups>
    </groups>
    <test name="MosaicTestApp" duration-ms="22866" started-at="2018-05-25T13:03:53Z" finished-at="2018-05-25T13:04:16Z">
      <class name="tests.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="setUp" is-config="true" duration-ms="1373" started-at="2018-05-25T13:03:53Z" finished-at="2018-05-25T13:03:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginElementsPresent()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="loginElementsPresent" duration-ms="113" started-at="2018-05-25T13:03:54Z" finished-at="2018-05-25T13:03:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginElementsPresent -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="tearDown" is-config="true" duration-ms="100" started-at="2018-05-25T13:03:54Z" finished-at="2018-05-25T13:03:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="setUp" is-config="true" duration-ms="1006" started-at="2018-05-25T13:03:55Z" finished-at="2018-05-25T13:03:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginWithNoCredentials()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="loginWithNoCredentials" duration-ms="303" started-at="2018-05-25T13:03:56Z" finished-at="2018-05-25T13:03:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login shouldn't work with no or invalid credentials expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login shouldn't work with no or invalid credentials expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at tests.LoginTest.loginWithNoCredentials(LoginTest.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithNoCredentials -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="tearDown" is-config="true" duration-ms="109" started-at="2018-05-25T13:03:56Z" finished-at="2018-05-25T13:03:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="setUp" is-config="true" duration-ms="968" started-at="2018-05-25T13:03:56Z" finished-at="2018-05-25T13:03:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginWithValidCredentials()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="loginWithValidCredentials" duration-ms="366" started-at="2018-05-25T13:03:57Z" finished-at="2018-05-25T13:03:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="tearDown" is-config="true" duration-ms="116" started-at="2018-05-25T13:03:57Z" finished-at="2018-05-25T13:03:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="setUp" is-config="true" duration-ms="937" started-at="2018-05-25T13:03:57Z" finished-at="2018-05-25T13:03:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="logoutTest()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="logoutTest" duration-ms="274" started-at="2018-05-25T13:03:58Z" finished-at="2018-05-25T13:03:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Click on Signout button is not working expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Click on Signout button is not working expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at tests.LoginTest.logoutTest(LoginTest.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.LoginTest@1b68ddbd]" name="tearDown" is-config="true" duration-ms="103" started-at="2018-05-25T13:03:59Z" finished-at="2018-05-25T13:03:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTest -->
      <class name="tests.APIResponseTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.APIResponseTest@59e5ddf]" name="setUp" is-config="true" duration-ms="922" started-at="2018-05-25T13:04:15Z" finished-at="2018-05-25T13:04:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="checkRateDataPresentInAPI()[pri:0, instance:tests.APIResponseTest@59e5ddf]" name="checkRateDataPresentInAPI" duration-ms="69" started-at="2018-05-25T13:04:16Z" finished-at="2018-05-25T13:04:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkRateDataPresentInAPI -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.APIResponseTest@59e5ddf]" name="tearDown" is-config="true" duration-ms="98" started-at="2018-05-25T13:04:16Z" finished-at="2018-05-25T13:04:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.APIResponseTest -->
      <class name="tests.DashboardTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.DashboardTest@646d64ab]" name="setUp" is-config="true" duration-ms="873" started-at="2018-05-25T13:03:59Z" finished-at="2018-05-25T13:04:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="assertColumnCount()[pri:0, instance:tests.DashboardTest@646d64ab]" name="assertColumnCount" duration-ms="1636" started-at="2018-05-25T13:04:00Z" finished-at="2018-05-25T13:04:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertColumnCount -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.DashboardTest@646d64ab]" name="tearDown" is-config="true" duration-ms="110" started-at="2018-05-25T13:04:01Z" finished-at="2018-05-25T13:04:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.DashboardTest@646d64ab]" name="setUp" is-config="true" duration-ms="943" started-at="2018-05-25T13:04:01Z" finished-at="2018-05-25T13:04:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="assertCurrencyInTableMatchesAPI()[pri:0, instance:tests.DashboardTest@646d64ab]" name="assertCurrencyInTableMatchesAPI" duration-ms="2316" started-at="2018-05-25T13:04:02Z" finished-at="2018-05-25T13:04:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertCurrencyInTableMatchesAPI -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.DashboardTest@646d64ab]" name="tearDown" is-config="true" duration-ms="102" started-at="2018-05-25T13:04:05Z" finished-at="2018-05-25T13:04:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.DashboardTest@646d64ab]" name="setUp" is-config="true" duration-ms="933" started-at="2018-05-25T13:04:05Z" finished-at="2018-05-25T13:04:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="assertNoEmptyCell()[pri:0, instance:tests.DashboardTest@646d64ab]" name="assertNoEmptyCell" duration-ms="1980" started-at="2018-05-25T13:04:06Z" finished-at="2018-05-25T13:04:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertNoEmptyCell -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.DashboardTest@646d64ab]" name="tearDown" is-config="true" duration-ms="104" started-at="2018-05-25T13:04:08Z" finished-at="2018-05-25T13:04:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.DashboardTest@646d64ab]" name="setUp" is-config="true" duration-ms="954" started-at="2018-05-25T13:04:08Z" finished-at="2018-05-25T13:04:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="assertRateInTableMatchesAPI()[pri:0, instance:tests.DashboardTest@646d64ab]" name="assertRateInTableMatchesAPI" duration-ms="2311" started-at="2018-05-25T13:04:09Z" finished-at="2018-05-25T13:04:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertRateInTableMatchesAPI -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.DashboardTest@646d64ab]" name="tearDown" is-config="true" duration-ms="102" started-at="2018-05-25T13:04:11Z" finished-at="2018-05-25T13:04:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.DashboardTest@646d64ab]" name="setUp" is-config="true" duration-ms="1063" started-at="2018-05-25T13:04:11Z" finished-at="2018-05-25T13:04:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="assertRowCountWithAPIDataSize()[pri:0, instance:tests.DashboardTest@646d64ab]" name="assertRowCountWithAPIDataSize" duration-ms="2448" started-at="2018-05-25T13:04:12Z" finished-at="2018-05-25T13:04:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The table row count doesnt match with api rate data count. Not all the currencies are fetched in the table from api expected [32] but found [10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The table row count doesnt match with api rate data count. Not all the currencies are fetched in the table from api expected [32] but found [10]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at tests.DashboardTest.assertRowCountWithAPIDataSize(DashboardTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertRowCountWithAPIDataSize -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.DashboardTest@646d64ab]" name="tearDown" is-config="true" duration-ms="104" started-at="2018-05-25T13:04:15Z" finished-at="2018-05-25T13:04:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.DashboardTest -->
    </test> <!-- MosaicTestApp -->
  </suite> <!-- MosaicSuite -->
</testng-results>
